"""Camada de acesso a dados do Meu Dinheiro.

Usa SQLAlchemy para funcionar tanto com **PostgreSQL** (produção, ex.: Neon)
quanto com **SQLite** (desenvolvimento local, sem configuração).

A URL de conexão é resolvida nesta ordem:
    1. st.secrets["DATABASE_URL"]        (Streamlit Cloud / secrets.toml)
    2. variável de ambiente DATABASE_URL
    3. SQLite local em data/meu_dinheiro.db  (fallback)

A senha do banco NUNCA fica no código — apenas em secrets/variáveis de ambiente.
"""

from __future__ import annotations

import os
from datetime import date
from functools import lru_cache

import pandas as pd
from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine

DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")
DB_PATH = os.path.join(DATA_DIR, "meu_dinheiro.db")

CATEGORIAS_PADRAO = [
    ("Salário", "receita", "#2E7D32"),
    ("Rendimentos", "receita", "#66BB6A"),
    ("Outras receitas", "receita", "#A5D6A7"),
    ("Moradia", "despesa", "#C62828"),
    ("Alimentação", "despesa", "#EF6C00"),
    ("Transporte", "despesa", "#F9A825"),
    ("Saúde", "despesa", "#AD1457"),
    ("Educação", "despesa", "#6A1B9A"),
    ("Lazer", "despesa", "#1565C0"),
    ("Compras", "despesa", "#00838F"),
    ("Contas e serviços", "despesa", "#4E342E"),
    ("Outras despesas", "despesa", "#546E7A"),
]

CONTAS_PADRAO = [
    ("Carteira", "dinheiro", 0.0),
    ("Conta corrente", "corrente", 0.0),
]


# --------------------------------------------------------------------------- #
# Engine / conexão
# --------------------------------------------------------------------------- #
def _database_url() -> str:
    # 1. Streamlit secrets (disponível quando rodando sob o Streamlit).
    try:
        import streamlit as st

        if "DATABASE_URL" in st.secrets:
            return str(st.secrets["DATABASE_URL"])
    except Exception:
        pass
    # 2. Variável de ambiente.
    url = os.environ.get("DATABASE_URL")
    if url:
        return url
    # 3. Fallback local: SQLite.
    os.makedirs(DATA_DIR, exist_ok=True)
    return f"sqlite:///{DB_PATH}"


@lru_cache(maxsize=1)
def get_engine() -> Engine:
    url = _database_url()
    if url.startswith("sqlite"):
        return create_engine(url, future=True)
    # Postgres (Neon e afins): pré-ping trata conexões ociosas/hibernadas.
    return create_engine(url, future=True, pool_pre_ping=True, pool_recycle=300)


def _is_sqlite() -> bool:
    return get_engine().dialect.name == "sqlite"


def _mes_expr(coluna: str) -> str:
    """Expressão SQL que extrai 'AAAA-MM' de uma coluna de data (TEXT)."""
    if _is_sqlite():
        return f"strftime('%Y-%m', {coluna})"
    return f"to_char(CAST({coluna} AS DATE), 'YYYY-MM')"


def _read(sql: str, params: dict | None = None) -> pd.DataFrame:
    with get_engine().connect() as conn:
        return pd.read_sql_query(text(sql), conn, params=params or {})


def _exec(sql: str, params) -> None:
    with get_engine().begin() as conn:
        conn.execute(text(sql), params)


# --------------------------------------------------------------------------- #
# Schema
# --------------------------------------------------------------------------- #
def init_db() -> None:
    """Cria as tabelas (se não existirem) e popula dados padrão."""
    sqlite = _is_sqlite()
    id_col = (
        "INTEGER PRIMARY KEY AUTOINCREMENT"
        if sqlite
        else "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    )
    real = "REAL" if sqlite else "DOUBLE PRECISION"

    ddl = [
        f"""
        CREATE TABLE IF NOT EXISTS contas (
            id            {id_col},
            nome          TEXT NOT NULL UNIQUE,
            tipo          TEXT NOT NULL DEFAULT 'corrente',
            saldo_inicial {real} NOT NULL DEFAULT 0
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS categorias (
            id   {id_col},
            nome TEXT NOT NULL,
            tipo TEXT NOT NULL CHECK (tipo IN ('receita', 'despesa')),
            cor  TEXT NOT NULL DEFAULT '#607D8B',
            UNIQUE (nome, tipo)
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS lancamentos (
            id           {id_col},
            data         TEXT NOT NULL,
            descricao    TEXT NOT NULL,
            valor        {real} NOT NULL,
            tipo         TEXT NOT NULL CHECK (tipo IN ('receita', 'despesa')),
            conta_id     INTEGER NOT NULL REFERENCES contas(id) ON DELETE CASCADE,
            categoria_id INTEGER REFERENCES categorias(id) ON DELETE SET NULL,
            pago         INTEGER NOT NULL DEFAULT 1
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS orcamentos (
            id           {id_col},
            categoria_id INTEGER NOT NULL REFERENCES categorias(id) ON DELETE CASCADE,
            competencia  TEXT NOT NULL,
            valor        {real} NOT NULL,
            UNIQUE (categoria_id, competencia)
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS metas (
            id          {id_col},
            nome        TEXT NOT NULL,
            valor_alvo  {real} NOT NULL,
            valor_atual {real} NOT NULL DEFAULT 0,
            prazo       TEXT
        )
        """,
    ]

    with get_engine().begin() as conn:
        for stmt in ddl:
            conn.execute(text(stmt))
        n_cat = conn.execute(text("SELECT COUNT(*) FROM categorias")).scalar()
        if n_cat == 0:
            conn.execute(
                text("INSERT INTO categorias (nome, tipo, cor) VALUES (:nome, :tipo, :cor)"),
                [{"nome": n, "tipo": t, "cor": c} for n, t, c in CATEGORIAS_PADRAO],
            )
        n_contas = conn.execute(text("SELECT COUNT(*) FROM contas")).scalar()
        if n_contas == 0:
            conn.execute(
                text(
                    "INSERT INTO contas (nome, tipo, saldo_inicial) "
                    "VALUES (:nome, :tipo, :saldo)"
                ),
                [{"nome": n, "tipo": t, "saldo": s} for n, t, s in CONTAS_PADRAO],
            )


# --------------------------------------------------------------------------- #
# Contas
# --------------------------------------------------------------------------- #
def listar_contas() -> pd.DataFrame:
    return _read("SELECT * FROM contas ORDER BY nome")


def criar_conta(nome: str, tipo: str, saldo_inicial: float) -> None:
    _exec(
        "INSERT INTO contas (nome, tipo, saldo_inicial) VALUES (:nome, :tipo, :saldo)",
        {"nome": nome.strip(), "tipo": tipo, "saldo": saldo_inicial},
    )


def excluir_conta(conta_id: int) -> None:
    _exec("DELETE FROM contas WHERE id = :id", {"id": conta_id})


def saldo_por_conta() -> pd.DataFrame:
    """Saldo atual = saldo inicial + receitas pagas - despesas pagas."""
    return _read(
        """
        SELECT c.id, c.nome, c.tipo, c.saldo_inicial,
               c.saldo_inicial
                 + COALESCE(SUM(CASE WHEN l.pago = 1 AND l.tipo = 'receita'
                                     THEN l.valor
                                     WHEN l.pago = 1 AND l.tipo = 'despesa'
                                     THEN -l.valor ELSE 0 END), 0) AS saldo_atual
        FROM contas c
        LEFT JOIN lancamentos l ON l.conta_id = c.id
        GROUP BY c.id, c.nome, c.tipo, c.saldo_inicial
        ORDER BY c.nome
        """
    )


# --------------------------------------------------------------------------- #
# Categorias
# --------------------------------------------------------------------------- #
def listar_categorias(tipo: str | None = None) -> pd.DataFrame:
    if tipo:
        return _read(
            "SELECT * FROM categorias WHERE tipo = :tipo ORDER BY nome",
            {"tipo": tipo},
        )
    return _read("SELECT * FROM categorias ORDER BY tipo, nome")


def criar_categoria(nome: str, tipo: str, cor: str) -> None:
    _exec(
        "INSERT INTO categorias (nome, tipo, cor) VALUES (:nome, :tipo, :cor)",
        {"nome": nome.strip(), "tipo": tipo, "cor": cor},
    )


def excluir_categoria(categoria_id: int) -> None:
    _exec("DELETE FROM categorias WHERE id = :id", {"id": categoria_id})


# --------------------------------------------------------------------------- #
# Lançamentos
# --------------------------------------------------------------------------- #
def criar_lancamento(
    data_lanc: date,
    descricao: str,
    valor: float,
    tipo: str,
    conta_id: int,
    categoria_id: int | None,
    pago: bool,
) -> None:
    _exec(
        """
        INSERT INTO lancamentos
            (data, descricao, valor, tipo, conta_id, categoria_id, pago)
        VALUES (:data, :descricao, :valor, :tipo, :conta_id, :categoria_id, :pago)
        """,
        {
            "data": data_lanc.isoformat(),
            "descricao": descricao.strip(),
            "valor": abs(valor),
            "tipo": tipo,
            "conta_id": conta_id,
            "categoria_id": categoria_id,
            "pago": int(pago),
        },
    )


def criar_lancamentos_em_lote(itens: list[dict]) -> int:
    """Insere vários lançamentos (parcelas, recorrências, importação)."""
    linhas = [
        {
            "data": item["data"].isoformat(),
            "descricao": item["descricao"].strip(),
            "valor": abs(float(item["valor"])),
            "tipo": item["tipo"],
            "conta_id": int(item["conta_id"]),
            "categoria_id": item.get("categoria_id"),
            "pago": int(item.get("pago", True)),
        }
        for item in itens
    ]
    if not linhas:
        return 0
    _exec(
        """
        INSERT INTO lancamentos
            (data, descricao, valor, tipo, conta_id, categoria_id, pago)
        VALUES (:data, :descricao, :valor, :tipo, :conta_id, :categoria_id, :pago)
        """,
        linhas,
    )
    return len(linhas)


def excluir_lancamento(lancamento_id: int) -> None:
    _exec("DELETE FROM lancamentos WHERE id = :id", {"id": lancamento_id})


def listar_lancamentos(
    inicio: date | None = None,
    fim: date | None = None,
    tipo: str | None = None,
) -> pd.DataFrame:
    """Retorna lançamentos com nomes de conta/categoria já resolvidos."""
    clausulas, params = [], {}
    if inicio:
        clausulas.append("l.data >= :inicio")
        params["inicio"] = inicio.isoformat()
    if fim:
        clausulas.append("l.data <= :fim")
        params["fim"] = fim.isoformat()
    if tipo:
        clausulas.append("l.tipo = :tipo")
        params["tipo"] = tipo
    where = ("WHERE " + " AND ".join(clausulas)) if clausulas else ""

    df = _read(
        f"""
        SELECT l.id, l.data, l.descricao, l.valor, l.tipo, l.pago,
               c.nome AS conta, cat.nome AS categoria, cat.cor AS cor
        FROM lancamentos l
        JOIN contas c ON c.id = l.conta_id
        LEFT JOIN categorias cat ON cat.id = l.categoria_id
        {where}
        ORDER BY l.data DESC, l.id DESC
        """,
        params,
    )
    if not df.empty:
        df["data"] = pd.to_datetime(df["data"])
    return df


# --------------------------------------------------------------------------- #
# Orçamentos
# --------------------------------------------------------------------------- #
def definir_orcamento(categoria_id: int, competencia: str, valor: float) -> None:
    _exec(
        """
        INSERT INTO orcamentos (categoria_id, competencia, valor)
        VALUES (:categoria_id, :competencia, :valor)
        ON CONFLICT (categoria_id, competencia)
        DO UPDATE SET valor = excluded.valor
        """,
        {"categoria_id": categoria_id, "competencia": competencia, "valor": valor},
    )


def orcamento_vs_realizado(competencia: str) -> pd.DataFrame:
    """Compara o orçado com o gasto (despesas pagas) em uma competência AAAA-MM."""
    return _read(
        f"""
        SELECT cat.nome AS categoria, cat.cor AS cor,
               COALESCE(o.valor, 0) AS orcado,
               COALESCE((
                   SELECT SUM(l.valor) FROM lancamentos l
                   WHERE l.categoria_id = cat.id
                     AND l.tipo = 'despesa' AND l.pago = 1
                     AND {_mes_expr('l.data')} = :competencia
               ), 0) AS gasto
        FROM categorias cat
        LEFT JOIN orcamentos o
               ON o.categoria_id = cat.id AND o.competencia = :competencia
        WHERE cat.tipo = 'despesa'
        ORDER BY cat.nome
        """,
        {"competencia": competencia},
    )


# --------------------------------------------------------------------------- #
# Metas de economia
# --------------------------------------------------------------------------- #
def listar_metas() -> pd.DataFrame:
    return _read("SELECT * FROM metas ORDER BY id")


def criar_meta(nome: str, valor_alvo: float, valor_atual: float, prazo) -> None:
    _exec(
        """
        INSERT INTO metas (nome, valor_alvo, valor_atual, prazo)
        VALUES (:nome, :alvo, :atual, :prazo)
        """,
        {
            "nome": nome.strip(),
            "alvo": float(valor_alvo),
            "atual": float(valor_atual),
            "prazo": prazo.isoformat() if prazo else None,
        },
    )


def atualizar_valor_meta(meta_id: int, novo_valor: float) -> None:
    _exec(
        "UPDATE metas SET valor_atual = :valor WHERE id = :id",
        {"valor": max(0.0, float(novo_valor)), "id": meta_id},
    )


def excluir_meta(meta_id: int) -> None:
    _exec("DELETE FROM metas WHERE id = :id", {"id": meta_id})
