"""Migra os dados do Meu Dinheiro de um PostgreSQL (origem) para outro (destino).

Copia apenas as tabelas deste app — contas, categorias, lancamentos, orcamentos,
metas e regras_categoria — preservando os IDs e as relações. Ignora quaisquer
outras tabelas que existam no banco de origem (ex.: de outro app).

Uso (a partir de uma máquina com acesso ao Neon, ex.: seu PC):

    pip install SQLAlchemy psycopg2-binary
    export SOURCE_URL="postgresql://...banco_antigo..."
    export DEST_URL="postgresql://...banco_novo..."
    python migrar_dados.py            # mostra um resumo e pede confirmação
    python migrar_dados.py --sim      # executa a migração sem perguntar
    python migrar_dados.py --dry-run  # só mostra o que existe na origem

ATENÇÃO: a migração APAGA os dados dessas tabelas no destino antes de copiar
(o destino fica idêntico à origem). Use um banco de destino dedicado a este app.
"""

from __future__ import annotations

import os
import sys

from sqlalchemy import create_engine, text

# Ordem de dependência (pais antes dos filhos).
TABELAS = ["contas", "categorias", "lancamentos", "orcamentos", "metas", "regras_categoria"]

# DDL PostgreSQL (idêntico ao usado pelo app) para garantir o schema no destino.
DDL = {
    "contas": """
        CREATE TABLE IF NOT EXISTS contas (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome TEXT NOT NULL UNIQUE,
            tipo TEXT NOT NULL DEFAULT 'corrente',
            saldo_inicial DOUBLE PRECISION NOT NULL DEFAULT 0
        )""",
    "categorias": """
        CREATE TABLE IF NOT EXISTS categorias (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome TEXT NOT NULL,
            tipo TEXT NOT NULL CHECK (tipo IN ('receita','despesa')),
            cor TEXT NOT NULL DEFAULT '#607D8B',
            UNIQUE (nome, tipo)
        )""",
    "lancamentos": """
        CREATE TABLE IF NOT EXISTS lancamentos (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            data TEXT NOT NULL,
            descricao TEXT NOT NULL,
            valor DOUBLE PRECISION NOT NULL,
            tipo TEXT NOT NULL CHECK (tipo IN ('receita','despesa')),
            conta_id INTEGER NOT NULL REFERENCES contas(id) ON DELETE CASCADE,
            categoria_id INTEGER REFERENCES categorias(id) ON DELETE SET NULL,
            pago INTEGER NOT NULL DEFAULT 1,
            transferencia INTEGER NOT NULL DEFAULT 0
        )""",
    "orcamentos": """
        CREATE TABLE IF NOT EXISTS orcamentos (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            categoria_id INTEGER NOT NULL REFERENCES categorias(id) ON DELETE CASCADE,
            competencia TEXT NOT NULL,
            valor DOUBLE PRECISION NOT NULL,
            UNIQUE (categoria_id, competencia)
        )""",
    "metas": """
        CREATE TABLE IF NOT EXISTS metas (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome TEXT NOT NULL,
            valor_alvo DOUBLE PRECISION NOT NULL,
            valor_atual DOUBLE PRECISION NOT NULL DEFAULT 0,
            prazo TEXT
        )""",
    "regras_categoria": """
        CREATE TABLE IF NOT EXISTS regras_categoria (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            palavra_chave TEXT NOT NULL,
            categoria_id INTEGER NOT NULL REFERENCES categorias(id) ON DELETE CASCADE
        )""",
}


def _url(nome: str) -> str:
    url = os.environ.get(nome, "").strip()
    if not url:
        sys.exit(f"Defina a variável de ambiente {nome} com a string de conexão.")
    return url


def _existe(conn, tabela: str) -> bool:
    return conn.execute(
        text(
            "SELECT 1 FROM information_schema.tables "
            "WHERE table_schema='public' AND table_name=:t"
        ),
        {"t": tabela},
    ).fetchone() is not None


def _colunas(conn, tabela: str) -> list[str]:
    rows = conn.execute(
        text(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_schema='public' AND table_name=:t ORDER BY ordinal_position"
        ),
        {"t": tabela},
    ).fetchall()
    return [r[0] for r in rows]


def main() -> None:
    dry = "--dry-run" in sys.argv
    auto = "--sim" in sys.argv or "-y" in sys.argv

    src = create_engine(_url("SOURCE_URL"), pool_pre_ping=True, future=True)
    dst = create_engine(_url("DEST_URL"), pool_pre_ping=True, future=True)

    # 1) Resumo da origem.
    print("\n=== Origem: tabelas do Meu Dinheiro encontradas ===")
    dados: dict[str, tuple[list[str], list[dict]]] = {}
    total = 0
    with src.connect() as c:
        for t in TABELAS:
            if not _existe(c, t):
                print(f"  {t:18s} — (não existe)")
                continue
            cols = _colunas(c, t)
            linhas = [dict(r._mapping) for r in c.execute(text(f"SELECT * FROM {t}"))]
            dados[t] = (cols, linhas)
            total += len(linhas)
            print(f"  {t:18s} — {len(linhas)} registro(s)")

    if total == 0:
        print("\nNada para migrar: a origem não contém dados do Meu Dinheiro.")
        return
    if dry:
        print("\n(--dry-run) Nenhuma alteração feita no destino.")
        return

    if not auto:
        resp = input(
            f"\nIsto vai APAGAR essas tabelas no destino e copiar {total} registro(s) "
            "da origem. Continuar? [s/N] "
        ).strip().lower()
        if resp not in ("s", "sim", "y", "yes"):
            print("Cancelado.")
            return

    # 2) Garante o schema no destino.
    with dst.begin() as c:
        for t in TABELAS:
            c.execute(text(DDL[t]))

    # 3) Limpa o destino e copia (na ordem de dependência).
    with dst.begin() as c:
        existentes = [t for t in TABELAS if _existe(c, t)]
        c.execute(text("TRUNCATE " + ", ".join(existentes) + " RESTART IDENTITY CASCADE"))

        for t in TABELAS:
            if t not in dados:
                continue
            cols_origem, linhas = dados[t]
            if not linhas:
                continue
            cols_destino = set(_colunas(c, t))
            # Copia apenas as colunas presentes em ambos os lados.
            cols = [col for col in cols_origem if col in cols_destino]
            col_list = ", ".join(cols)
            val_list = ", ".join(f":{col}" for col in cols)
            c.execute(
                text(f"INSERT INTO {t} ({col_list}) VALUES ({val_list})"),
                [{col: linha.get(col) for col in cols} for linha in linhas],
            )
            # Reajusta a sequência do id para não colidir em inserções futuras.
            c.execute(
                text(
                    f"SELECT setval(pg_get_serial_sequence('{t}', 'id'), "
                    f"GREATEST((SELECT COALESCE(MAX(id), 1) FROM {t}), 1))"
                )
            )
            print(f"  copiado: {t:18s} {len(linhas)} registro(s)")

    # 4) Conferência.
    print("\n=== Conferência no destino ===")
    with dst.connect() as c:
        for t in TABELAS:
            if _existe(c, t):
                n = c.execute(text(f"SELECT COUNT(*) FROM {t}")).scalar()
                print(f"  {t:18s} — {n} registro(s)")
    print("\nMigração concluída com sucesso. ✅")


if __name__ == "__main__":
    main()
